/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#12131b',
        background: '#12131b',
        'on-surface': '#e3e1ed',
        'on-background': '#e3e1ed',
        'on-surface-variant': '#c2c6d7',
        'surface-dim': '#12131b',
        'surface-bright': '#383842',
        'surface-container': '#1e1f28',
        'surface-container-low': '#1a1b23',
        'surface-container-high': '#292932',
        'surface-container-highest': '#33343d',
        'surface-container-lowest': '#0d0e16',
        'surface-variant': '#33343d',
        'surface-tint': '#b2c5ff',
        primary: '#b2c5ff',
        'on-primary': '#002b73',
        'primary-container': '#5c8cff',
        'on-primary-container': '#002565',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        'on-primary-fixed': '#001848',
        'on-primary-fixed-variant': '#0040a2',
        'inverse-primary': '#0055d3',
        secondary: '#d8b9ff',
        'on-secondary': '#450086',
        'secondary-container': '#6904c5',
        'on-secondary-container': '#d0acff',
        'secondary-fixed': '#eedcff',
        'secondary-fixed-dim': '#d8b9ff',
        'on-secondary-fixed': '#290055',
        'on-secondary-fixed-variant': '#6300bb',
        tertiary: '#00dfc1',
        'on-tertiary': '#00382f',
        'tertiary-container': '#00a38d',
        'on-tertiary-container': '#003028',
        'tertiary-fixed': '#26fedc',
        'tertiary-fixed-dim': '#00dfc1',
        'on-tertiary-fixed': '#00201a',
        'on-tertiary-fixed-variant': '#005144',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#8c90a0',
        'outline-variant': '#424654',
        'inverse-surface': '#e3e1ed',
        'on-primary-fixed': '#001848',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
      },
      spacing: {
        base: '4px',
        'sidebar-width': '280px',
        'header-height': '64px',
        'section-margin': '48px',
        'element-gap': '16px',
        'container-padding': '24px',
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Geist', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist', 'system-ui', 'sans-serif'],
        'display-lg': ['Geist', 'system-ui', 'sans-serif'],
        'mono-code': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      maxWidth: {
        chat: '1024px',
      },
    },
  },
  plugins: [],
}
